print(bool(0))
print(bool(0.0))
print(bool(""))
print(bool(None))
print(bool([]))
print(bool(list()))
print(bool(()))
print(bool({}))
print(bool(False))
print('-----------------------------')
print(bool(10))
print(bool('s'))
print(bool([10, 30]))
print(bool({'key': 'value'}))
print(bool((10, 50, 20)))
print(bool(True))
