import requests
from bs4 import BeautifulSoup

response = requests.get('http://www.baidu.com')
html = response.content.decode()
soup = BeautifulSoup(html, 'lxml')
print('--------根据标签名称来查找--------')
meta = soup.find('meta')
print(meta)
print('---------------------')
metas = soup.find_all('meta')
print(metas)
print('--------根据属性来查找--------')
a = soup.find(rel='stylesheet')
print(a)
print('---------------------')
b = soup.find(attrs={'rel': 'stylesheet'})
print(b)
print('--------根据文本来查找--------')
c = soup.find(text='关于百度')
print(c)
print('---------------------')
print(type(b))
print(b.name)
print(b.attrs)
print(b.text)

print('---------------------')
aTag = soup.find('a')
print(aTag)

print('tag的名称为', aTag.name)
print('tag的属性为', aTag.attrs)
print('tag的文本为', aTag.text)
